name: Surfboard
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_native_splash: ^1.2.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
flutter_native_splash:
  color: "#42a5f5"
  image: lib/assets/logo1.png
  andriod: true
  ios: true
  fullscreen: true



